# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s3:
      dhcp4: false
      addresses:
        - 192.168.97.81/22
      routes:
        - to: default
          via: 192.168.96.1
      nameservers:
        addresses: [192.168.97.80]
  version: 2
